---
title: "Project title"
subtitle: "STA/ISS 313 - Project 1"
author: "Visualization Warriors"
format: html
editor: visual
---

## Abstract

(1 paragraph): Project abstract.

------------------------------------------------------------------------

## Introduction

The `pell` data set was featured on TidyTuesday in 2022. It contains information on the distribution of pell grant awards to college students in the United States from 1999-2017. This data set is a compilation of yearly datasets collected by the US Department of Education. The original yearly data was reported by the USDE in different ways across the years, after which it was cleaned up to become the \`pell\` data set that will be used in this project. 

The `pell` data set contains 100470 cases of Pell grant awards and contains 4 missing values. It explores the award amount in each school for each respective year represented in the data set. The variables in this data set include the state in which the school's located, the total Pell grant award the school gave, the number of students at the school who received a Pell grant, the name of the school, the session year, and the year. Specifically, the variables `NAME`, `FACTOR`, and `SESSION` are all factor variables while the other variables are numeric. There are some important notes to keep in mind when interpreting the data set. Firstly, the variable `STATE` includes both US states and territories, meaning there are more than 50 possible observation types. Finally, the difference between `SESSION` and `YEAR` is that `SESSION` indicates the academic school year (which is between two numeric years)

\

## Question 1: Need title.

### Introduction

(1-2 paragraphs): Introduction to the question and what parts of the dataset are necessary to answer the question. Also discuss why you're interested in this question.

### Approach

(1-2 paragraphs): Describe what types of plots you are going to make to address your question. For each plot, provide a clear explanation as to why this plot (e.g. boxplot, barplot, histogram, etc.) is best for providing the information you are asking about. The two plots should be of different types, and at least one of the two plots needs to use either color mapping or facets.

The raw data set contains six columns of information: the state in which the school's located, the total Pell grant award the school gave, the number of students at the school who received a Pell grant, the name of the school, the session year, and the year. In order to solve the question of how the average Pell grant award changes over time based on the region, we first need two additional variables: the **average pell grant** for school and **region.** The 'average pell grant' variable will be calculated by dividing the total Pell grant award by the number of students who received the award. The 'region' variable will be mutated by returning the region based on the school's state.

We plan to find a data set containing two columns, the name of each of the 50 states and the region in the United States for each other the 50 states. We will join that dataset with our pell grant data set by state. A line graph will most likely be implemented to answer this question, since we're seeking to check a numerical variable's progression over time. In the end, we hope to have a region-by-region understanding of Pell grant awards and their changes over time. Then we can differentiate the line graphs by region through faceting for each region. Another option would be implementing one individual line graph that has all the lines for each region, so that we can see more clearly how each region compares to one another. The x-variable would be each year provided in the data. 

Additionally, we plan to make a second, more visually appealing spatial graph to evaluate change over time. We plan to group the colleges by individual states and different time periods, finding their average pell grant. The time periods will be broken up by presidential terms, hoping to find some interesting correlations and trends concerning real-world events that have taken place. The visualization will display a map of the United States, and each individual state will be a particular shade of a certain color. The darker shade on the graph will represent a higher average pell grant.  We hope to facet by the time period (election term) for comparison purposes. Solving this will require extracted information on the location coordinates for each state, for the purposes of making the map visualization. Possibly implementing a Google maps API or the 'ggmap' library package will assist us in creating this graph. 

In the end, we hope to have a region-by-region understanding of pell grant awards and their changes over time.

### Analysis

(2-3 code blocks, 2 figures, text/code comments as needed): In this section, provide the code that generates your plots. Use scale functions to provide nice axis labels and guides. You are welcome to use theme functions to customize the appearance of your plot, but you are not required to do so. All plots must be made with **ggplot2**. Do not use base R or lattice plotting functions.

```{r creation-of-variables}
#load the region data set + join to original (be sure to account for the territories)
library(tidyverse)
pell <- read_csv("data/pell.csv")
regions <- read_csv("data/region.csv")

pell2 <- inner_join(pell, regions) #decided to drop all territories

#began creating the avg_pell_award data
pell2 %>% 
  drop_na() %>% 
  group_by(YEAR) %>% 
  mutate(AVG_PELL_AWARD = mean(AWARD))
```

``` {visualization-1-time}

```

### Discussion

(1-3 paragraphs): In the Discussion section, interpret the results of your analysis. Identify any trends revealed (or not revealed) by the plots. Speculate about why the data looks the way it does.

## Question 2: Title that relates to the question you're answering

### Introduction

(1-2 paragraphs): Introduction to the question and what parts of the dataset are necessary to answer the question. Also discuss why you're interested in this question.

### Approach

(1-2 paragraphs): Describe what types of plots you are going to make to address your question. For each plot, provide a clear explanation as to why this plot (e.g. boxplot, barplot, histogram, etc.) is best for providing the information you are asking about. The two plots should be of different types, and at least one of the two plots needs to use either color mapping or facets.

From the raw data set, we will use the state in which the school is located, the total amount of Pell grant recipients for each year, and the year. We will summarize the data to just get the amount of Pell recipients by state by year. From there, we will incorporate enrollment data for the total amount of students enrolled in university by state by year. With that data, we will be able to calculate the proportion of students who are enrolled in university receiving a Pell Grant by dividing amount of recipients by state by year by total undergrads enrolled by state by year.

For our first visualization, we plan to use a line graph to visualize the proportion of students receiving a pell grant over time in each state. We will do this by having a line for each of the 50 states and having a very low alpha value for most of them, with a few that we want to highlight having a higher alpha level. This will allow us to clearly show a few notable stats over the top of the general trend for all of the states. For our second visualization, we plan to get the coordinates for each college by using a google maps API and then plotting a dot at each college. The dot will be sized based on the amount of pell grant recipients at the school and colored by the proportion of students receiving a pell grant. We then will put a few of these maps side by side each representing a different time period, possibly corresponding to presidential cycle. This will allow us to see trends in states and areas in both amounts of students and proportions.

### Analysis

(2-3 code blocks, 2 figures, text/code comments as needed): In this section, provide the code that generates your plots. Use scale functions to provide nice axis labels and guides. You are welcome to use theme functions to customize the appearance of your plot, but you are not required to do so. All plots must be made with **ggplot2**. Do not use base R or lattice plotting functions.

### Discussion

(1-3 paragraphs): In the Discussion section, interpret the results of your analysis. Identify any trends revealed (or not revealed) by the plots. Speculate about why the data looks the way it does.
